Edits A Rules File:
- "./Code of Conduct.md"
- "./.github/Contributing.md"

Edits Code Owners File:
- "./.github/CODEOWNERS"

Edits Important Website Files:
- "./_config.yml"
- "./Gemfile"

Edits Issue Templates:
- "./.github/ISSUE_TEMPLATE/*"

Edits License Files:
- "./License"
- "./_github-no/L Page.md"

Edits Workflow Files:
- "./.github/workflows/*"