name: Maintain new pull requests

on:
  pull_request_target:
    types: [opened]

jobs:
  MaintainBOBPost:
    name: Maintain pull request by BOB
    runs-on: windows-latest
    if: ${{ github.event.sender.login == 'TheOneBOB' }}
    timeout-minutes: 60
    steps:
    - name: Assign BOB to pull request
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.KEY }}" -H "Accept: application/vnd.github.v3+json" -d "{ \""assignees\"": [\""TheOneBOB\""]}" --url "https://api.github.com/repos/BOBDevStudio/RBAP-Wiki/issues/${{ github.event.pull_request.number }}/assignees"
  MaintainUnbitternessPost:
    name: Maintain pull request by Unbitterness
    runs-on: windows-latest
    if: ${{ github.event.sender.login == 'Valexiwasgone' }}
    timeout-minutes: 60
    steps:
    - name: Assign Unbitterness to pull request
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.KEY }}" -H "Accept: application/vnd.github.v3+json" -d "{ \""assignees\"": [\""Valexiwasgone\""]}" --url "https://api.github.com/repos/BOBDevStudio/RBAP-Wiki/issues/${{ github.event.pull_request.number }}/assignees"