name: Label pull requests

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, closed, synchronize]

jobs:
  Run:
    name: Run
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'TheOneBOB' || github.event.pull_request.user.login == 'BOBDevStudioBot' || github.event.pull_request.user.login == 'Valexiwasgone' }}
    timeout-minutes: 60
    steps:
    - name: Run labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.KEY }}"
        configuration-path: ".github/labeler.yml"
        sync-labels: true