name: Label pull requests

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, closed, synchronize]

jobs:
  Run:
    name: Run (normally)
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' && github.event.pull_request.user.login == 'TheOneBOB' || github.event.pull_request.user.login == 'BOBDevStudioBot' || github.event.pull_request.user.login == 'Valexiwasgone' }}
    timeout-minutes: 60
    steps:
    - name: Run labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.KEY }}"
        configuration-path: ".github/labeler.yml"
        sync-labels: true
  RunFromLable:
    name: Run (from label)
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'Labeler Run' && github.event.sender.login == 'TheOneBOB' }}
    timeout-minutes: 60
    steps:
    - name: Remove trigger label
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.KEY }}" -H "Accept: application/vnd.github.v3+json" --url "https://api.github.com/repos/BOBDevStudio/RBAP-Wiki/issues/${{ github.event.pull_request.number }}/labels/Labeler%20Run"
    - name: Run labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.KEY }}"
        configuration-path: ".github/labeler.yml"
        sync-labels: true